# **Series**

**Creating a Series**  
*series are one dimensional*

In [1]:
import numpy as np
import pandas as pd
labels=['a', 'b','c'] #these are the indexes
list=[10,20,30]  # creating a list
arr=np.array([10,20,30]) #creating an array
d={1:10,2:20,3:30} #creating a dicitonary

ModuleNotFoundError: No module named 'numpy'

In [ ]:
pd.Series(labels) #labels to series

0    a
1    b
2    c
dtype: str

In [ ]:
pd.Series(list) #list to series

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr) # array to series

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d) # dictionary ( its keys) to series

1    10
2    20
3    30
dtype: int64

In [ ]:
pd.Series(list,index=labels) #creating a custom indexing by giving "labels" as index values

a    10
b    20
c    30
dtype: int64

# **DataFrames**

**Creating a DataFrame**  
*dataframes are multi dimensional*

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data) #creating a dataframe from the data which is dicitonary
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list) #creating a dataframe from the data which is list
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
mycol = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =mycol) #providing the custom indexing by giving "coloumns" its value from "mycol"
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting and Indexing of Coloumns**

In [ ]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [ ]:
df[['Name', 'City']] # selecting multiple coloumns

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a New Coloumn**

In [ ]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Coloumns**

In [ ]:
df3=df2.drop('Salary',axis=1) #axus 1 is the coloummn
df3

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

In [ ]:
df2 # see, the salary has not been removed from the main data

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [ ]:
df2.drop('Salary',axis=1,inplace=True) #inplace means remove completely from the maindata
df2

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

**Removing Rows**

In [ ]:
df2.drop(0,axis=0) # axis 0 means row

    Name  Age    City Designation
1   Anna   34   Paris        Eng.
2  Peter   29  Berlin      Doctor
3  Linda   42  London        Eng.

**Selecting Rows**

In [ ]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df.loc[[0,1,2]] #selectign multiple rows

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [ ]:
df.iloc[0] #selecting item which is at the locatin( index) of 0

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df.iloc[[0,1,2]] #selecting multiple items which is at the locatin( index) of 0, and 1 and 2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

**Selecting subsets of Rows and Coloumns**

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection**

In [ ]:
df2

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

In [ ]:
df2[df2['Age']>32]

    Name  Age    City Designation
1   Anna   34   Paris        Eng.
3  Linda   42  London        Eng.

In [ ]:
df2[(df2['Age']>32) & (df2['City']=='Paris')]

   Name  Age   City Designation
1  Anna   34  Paris        Eng.

In [ ]:
df2[(df2['Age']>32) | (df2['City']=='Paris')]

    Name  Age    City Designation
1   Anna   34   Paris        Eng.
3  Linda   42  London        Eng.

# **Missing Data**

**Finding The Missing Data**

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna() #find where are missing data

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum() #find the sum ciunt of missing data

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any() #find whether there is any missing data in anny row

A     True
B    False
C     True
D     True
dtype: bool

**Removing Null Values**

In [ ]:
df.dropna() #drop the rows containing missing data

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) # drop the rows which are containing min 3 null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Filling Null Values**

In [ ]:
df.fillna(433) # fill all null values with 433

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  433.0
2  433.0  3    3.0  433.0
3    4.0  4  433.0  433.0
4    5.0  5  433.0    5.0

In [ ]:
df.fillna("I was a Null Value")

                    A  B                   C                   D
0                 1.0  1                 1.0                 1.0
1                 2.0  2                 2.0  I was a Null Value
2  I was a Null Value  3                 3.0  I was a Null Value
3                 4.0  4  I was a Null Value  I was a Null Value
4                 5.0  5  I was a Null Value                 5.0

In [ ]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# **Merging, Joining and Concatenating two DataFrames**

**Merging 2 DataFrames**

In [ ]:
# DataFrame 2: Emplyoee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries) # merge the two dataframes BUT only which are common in both

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id') # merge two dataframes, BUT which are common, and common should be employee_id

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='inner') 
# merge two dataframes, BUT which are common, and common should be employee_id, BUT "OUTER" means include all the values which are only common.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='outer') 
# merge two dataframes, BUT which are common, and common should be employee_id, BUT "OUTER" means include all the values which are not common also

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='left') 
#merge two data frames, common should be merged, search common on basis of employee, 
# "left" means include all the emplyoee id which are in emplyoe_id
# because ( emplyoees, salaries), employee on the left

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatenation of 2 DataFrames**

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2]) # by default axis is row =0, row wise concat

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2],axis= 1) # col wise

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 DataFrames**

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df1.join(df2,how='outer') # "outer" means include all the values of df1 no matter it exist in df2 or not

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# **GroupBy, Aggregation**

**Group by Category and calculate the sum of Sales**

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
cat = df.groupby('Category')['Sales'].sum() # calculate sum of sales into all the categories
cat

Category
A    570
B    930
Name: Sales, dtype: int64

**Group by multiple columns :**
Group by Category and Store

In [ ]:
cat = df.groupby(['Category','Store'])['Sales'].sum() # calculate sum of sales into all the category and into all the stores
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [ ]:
""" only one aggregate function """
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

# **Pivot Tables and Cross Tabs**

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    523     74   John  January      Q1
1  2023-01-02       B   West    307     20   Mary  January      Q1
2  2023-01-03       C  North    432     90    Bob  January      Q1
3  2023-01-04       D  South    233     28  Alice  January      Q1
4  2023-01-05       A   East    504     49   John  January      Q1
5  2023-01-06       B   West    577     40   Mary  January      Q1
6  2023-01-07       C  North    995     32    Bob  January      Q1
7  2023-01-08       D  South    353     58  Alice  January      Q1
8  2023-01-09       A   East    648     32   John  January      Q1
9  2023-01-10       B   West    714     90   Mary  January      Q1
10 2023-01-11       C  North    272     49    Bob  January      Q1
11 2023-01-12       D  South    428     76  Alice  January      Q1
12 2023-01-13       A   East    571     43   John  January      Q1
13 2023-01-14       B   West    869     42   Mary  January      Q1
14 2023-01-15       C  North    240     91    Bob  January      Q1
15 2023-01-16       D  South    729     26  Alice  January      Q1
16 2023-01-17       A   East    956     46   John  January      Q1
17 2023-01-18       B   West    237     40   Mary  January      Q1
18 2023-01-19       C  North    545     50    Bob  January      Q1
19 2023-01-20       D  South    402     95  Alice  January      Q1

In [ ]:
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product', aggfunc='median') 
#create pivot table from dataframe "df"
# but include only 2 values for pivot tables= "sales", "units" AND values must  be numeric
# the values should have for all the "reigions"->index,
# coloumns should be "product"
# 
# this aggregation function is optional, by defualt it's mean, # HERE WE USE AGGREGATE FUCNTIONS


# sales and unit values for different products different regions

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     640.4    NaN    NaN    NaN  48.8   NaN   NaN   NaN
North      NaN    NaN  496.8    NaN   NaN   NaN  62.4   NaN
South      NaN    NaN    NaN  429.0   NaN   NaN   NaN  56.6
West       NaN  540.8    NaN    NaN   NaN  46.4   NaN   NaN

In [ ]:
pd.crosstab(df['Region'],df['Product'])
# cross tab from the dataframe's -> Region coloumn and Product coloumn
# HERE WE USE COUNTING FUCNTIONS

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# **DataFrames Operations**

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [ ]:
df1['D'] = df1["B"].apply(lambda x : x**2)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500