In [1]:
#loading the data
import numpy as np 
import pandas as pd

In [ ]:
# reading the data
df = pd.read_csv(r'FeatureExtractionAnime.csv') #our dataframe
df.head() # top 5 rows

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [ ]:
df.loc[4]['Title'] # check the title of index number 4

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

**Make a new coloumn separately for Episode Count: here we will use feature extraction**

In [13]:
#for this i will create a function
def extract_episodes(txt): # this text is the "title" of the index numbers
    check=False
    data='' # here i will extract the data of count of episodes
    
    for i in txt:
        if i==')':
            break # if bracket is closed, break it
        
        if check==True:
            data+=i # extract when the check is true
            
        if i=='(':
            check=True #if bracket is open, continue for next step
    return data
# now i will apply this function on Each title of my data  AND from each title, i will extract count of episoded

In [21]:
#create a new coloumn
df["Episodes"]=df["Title"].apply(extract_episodes)
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [22]:
# now converting the count of episodes into numerical data
df['Episodes']= df['Episodes'].str.replace(" eps","")
#now convert these episodes into integer because these are string
df["Episodes"]=df["Episodes"].astype(int)
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

**make a new column for time stamp**

In [ ]:
df.loc[2]['Title'] # watch closely the time stamp : "Apr 2015 - Mar 2016" : total  19 is its length

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [27]:
def extraction_time(txt):
    check = False
    data = "" # here i will extract the data of count of episodes
    for i in range(len(txt)):
        if txt[i] == ')': # time stamp start after ")"
            for j in range(i+1,i+20): # start extracting data 20 steps more from one step forward to the pointer
                data += txt[j]

            return data
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [28]:
# create a new coloumn and apply above function
df['Total Time'] = df['Title'].apply(extraction_time)
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

**create a new coloumn of months count**

In [29]:
# Import relativedelta to calculate the difference between two dates in years and months
from dateutil.relativedelta import relativedelta

# Import datetime to convert string dates into datetime objects
from datetime import datetime


# Function to calculate the total number of months from a given time period
def calculate_total_months(period):
    try:
        # Split the string into start and end dates
        # Example: "Jan 2018 - Mar 2020"
        # start_str = "Jan 2018"
        # end_str = "Mar 2020"
        start_str, end_str = period.split(' - ')

        # Convert the start and end date strings into datetime objects
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')

        # Calculate the difference between the two dates
        r = relativedelta(end_date, start_date)

        # Convert years into months and add the remaining months
        # +1 is added to include the starting month
        # Example:
        # Jan 2020 to Mar 2020
        # Difference = 2 months
        # Including Jan = 3 months
        total_months = r.years * 12 + r.months + 1

        return total_months

    # If the date format is invalid or missing, return None
    except:
        return None


# Apply the function to every value in the 'Total Time' column
# and store the result in a new column called 'Months'
df['Months'] = df['Total Time'].apply(calculate_total_months)
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4